export {
  YandexWebmasterError,
  AuthError,
  NotFoundError,
  ValidationError,
  RateLimitError,
  ConflictError,
  ServerError,
  createApiError,
} from './errors.js';

export type {
  UserInfo,
  Host,
  HostList,
  HostSummary,
  SiteProblem,
  Sitemap,
  SitemapList,
  IndexingStatus,
  IndexingHistoryEntry,
  SearchUrlInfo,
  SearchUrlList,
  ImportantUrl,
  ImportantUrlIssue,
  ImportantUrlList,
  SearchQueryIndicator,
  SearchQueryEntry,
  SearchQueryResult,
  ExternalLink,
  ExternalLinkList,
  SQIHistoryEntry,
  SQIHistory,
  DiagnosticsEntry,
  DiagnosticsInfo,
  RecrawlQuota,
  RecrawlTask,
  RecrawlTaskList,
  OriginalText,
  OriginalTexts,
  OriginalTextQuota,
  Owner,
  OwnerList,
  VerificationInfo,
  SearchEventInfo,
  SearchEventList,
  BrokenLink,
  BrokenLinkList,
  Feed,
  FeedList,
  FeedUploadStatus,
  QueryAnalyticsRequest,
  QueryAnalyticsResult,
  DateRange,
  Pagination,
  SearchQueryParams,
} from './types.js';

export { YandexWebmasterClient } from './yandex-webmaster-client.js';
